@echo Compile programm...
@echo off
C:/TDM-GCC-32/bin/g++.exe -fdiagnostics-color=always -g C:\Users\acer\Desktop\graphics_labs\main.cpp -o C:\Users\acer\Desktop\graphics_labs\main.exe -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32  
@echo Run application...
.\main.exe